# ui.R

library(shiny)
library(leaflet)
library(DT)
library(shinythemes)

source("helpers.R") # Optional: use this if you move utility functions to a separate helpers.R file

# Module UI for weather input
weatherInputUI <- function(id) {
  ns <- NS(id)
  tagList(
    radioButtons(
      ns("data_source"), 
      "Choose Data Source", 
      choices = c("Use Visual Crossing API" = "api", "Upload CSV File" = "csv", "Demo Data" = "demo"), 
      selected = "api"
    ),
    conditionalPanel(
      condition = "input.data_source == 'api'",
      ns = ns,
      textInput(ns("api_key"), "Enter API Key", ""),
      dateRangeInput(ns("date_range"), "Select Date Range",
                     start = Sys.Date() - 180, end = Sys.Date()),
      textAreaInput(ns("coordinates"), "Enter Latitude, Longitude, and ID (one per line, format: 'lat, lon, ID')", 
                    "70.3706, 31.1107, Varanger\n63.4305, 10.3951, Trøndelag"),
      actionButton(ns("fetch"), "Fetch Weather Data")
    ),
    conditionalPanel(
      condition = "input.data_source == 'csv'",
      ns = ns,
      fileInput(ns("csv_file"), "Upload CSV File", accept = ".csv")
    ),
    downloadButton(ns("download"), "Download CSV")
  )
}

# Module UI for plotting
weatherPlotUI <- function(id) {
  ns <- NS(id)
  tagList(
    leafletOutput(ns("map"), height = "400px"),
    plotOutput(ns("plot_temp")),
    plotOutput(ns("plot_degree_days")),
    plotOutput(ns("plot_tsi"))
  )
}

ui <- fluidPage(theme = shinytheme("cerulean"),
    tags$div(class = "jumbotron text-center", style = "margin-bottom:0px;margin-top:0px",
             tags$h2(class = 'jumbotron-heading', stye = 'margin-bottom:0px;margin-top:0px', 'Hjernemark / Livtsja-vikke risiko app'),
             p('Reindeer brainworm risk app')
    ),

  sidebarLayout(
    sidebarPanel(
      img(src='reindeer.jpg', align = "left", width = "100%"),
      weatherInputUI("weatherInput")
    ),
    
    mainPanel(
      div(
        "**Development version for veterinarians** This app is intended for use by veterinarians to help reindeer herders assess the risk of brainworm transmission based on recent weather conditions. Feedback is very welcome - please get in touch (hannah.vineer@liverpool.ac.uk)",
        style = "margin-top: 10px; font-size: 16px; font-weight: bold; color = #555;"
      ),
      div(
        HTML("
        <button class='btn btn-link' data-toggle='collapse' data-target='#additionalInfo' style='margin-top: 15px;'>
          About the predictions (click to expand)
        </button>
        <div id='additionalInfo' class='collapse'>
          <p style='font-size: 14px; font-style: italic; color: #555;'>
            This app runs a brainworm Thermal Suitability Index (TSI) model (https://doi.org/10.3389/fvets.2020.603990) which uses daily weather data for your chosen locations to predict the approximate *timing* of brainworm transmission. Please note that the predictions generated by this app will be very sensitive to the date range of the data you request, and therefore the app must be used in collaboration with a veterinarian with expertise in brainworm.
          </p>
        </div>
      ")
      ),
      div(
        HTML("
        <button class='btn btn-link' data-toggle='collapse' data-target='#runInfo' style='margin-top: 15px;'>
          How to run the app - using Visual Crossing weather API (click to expand)
        </button>
        <div id='runInfo' class='collapse'>
          <p style='font-size: 14px; font-style: italic; color: #555;'>
            Based on your understanding of brainworm epidemiology and larval shedding in your region, choose an appropriate start date for the model predictions e.g. you may choose autumn to predict the timing of potential transmission of larvae shed by infected reindeer at this time of year. You will need to sign up for a free account at VisualCrossing.com and copy your API Key (can be found in the account section) to access the weather data. Once you have your API key, please input your requested locations for model predictions. We have added some default locations as examples and for users wishing to explore the app quickly. Bear in mind that the number of free records available through VisualCrossing is limited to 1000 per day, and therefore predicting TSI for a large number of locations over extended poeriods may not be possible with a free account.
           </p>
        </div>
      ")
      ),
      div(
        HTML("
        <button class='btn btn-link' data-toggle='collapse' data-target='#runInfo' style='margin-top: 15px;'>
          How to run the app - using your own weather data (click to expand)
        </button>
        <div id='runInfo' class='collapse'>
          <p style='font-size: 14px; font-style: italic; color: #555;'>
            If you already have your own weather data, you can upload this as a .csv file. The file must be formatted as follows: columns with the headers 'date', 'lat', 'lon', 'ID', 'mean_temp'. 'date' must be formatted as 'YYYY-MM-DD', for example, 1st of October 2024 would be '2024-10-01'. 'lat' and 'lon' are the latitudes and longitudes for the locations in your dataset, in *decimal degrees*. 'ID' is the name you give each location in your dataset, and will be used to label the visualisations produced by the app. Please keep these simple to avoid errors running the app. If you have multiple locations in your dataset, the data for each location should cover the same date range. *Troubleshooting* If your data upload fails or the temperature data look unusual/unexpected, you may have issues with special characters or incorrect formatting of dates.
            </p>
        </div>
      ")
      ),
      div(
        HTML("
        <button class='btn btn-link' data-toggle='collapse' data-target='#interpretInfo' style='margin-top: 15px;'>
          Interpreting predictions (click to expand)
        </button>
        <div id='interpretInfo' class='collapse'>
          <p style='font-size: 14px; font-style: italic; color: #555;'>
            Interpreting the output: The app will provide a map of your chosen locations, colour-coded according to the TSI value based on the date range you specified. Click on the points to expand the information and view the TSI values. TSI>1 indicates that transmission is theoretically possible at that location based on the mean temperature data returned by the weather service and the assumption that larvae were shed at the beginning of your requested date range. This represents the HAZARD component of risk assessment and should be interpreted in combination with local knowledge of exposure to potential infection (e.g. are reindeer grazing in that area) and vulnerability (e.g. age and reproductive status, coinfection, nutritional/environmental stress). The app also provides the temperature data and model output for you to inspect/critically evalluate and download for reanalysis/archive.
           </p>
        </div>
      ")
      ),
      weatherPlotUI("weatherPlot"),
      dataTableOutput("table")
    )
  )
)
