# ui.R

library(shiny)
library(leaflet)
library(DT)
library(shinythemes)
library(plotly)

source("helpers.R") # Optional: use this if you move utility functions to a separate helpers.R file

# Module UI for weather input
weatherInputUI <- function(id) {
  ns <- NS(id)
  tagList(
    radioButtons(
      ns("data_source"), 
      "Choose Data Source", 
      choices = c("Use Visual Crossing API" = "api", "Upload CSV File" = "csv", "Demo Data" = "demo"), 
      selected = "api"
    ),
    conditionalPanel(
      condition = "input.data_source == 'api'",
      ns = ns,
      textInput(ns("api_key"), "Enter API Key", ""),
      dateRangeInput(ns("date_range"), "Select Date Range",
                     start = Sys.Date() - 180, end = Sys.Date()),
      textAreaInput(ns("coordinates"), "Enter Latitude, Longitude, and ID (one per line, format: 'lat, lon, ID')", 
                    "70.3706, 31.1107, Varanger\n63.4305, 10.3951, Trøndelag"),
      actionButton(ns("fetch"), "Fetch Weather Data")
    ),
    conditionalPanel(
      condition = "input.data_source == 'csv'",
      ns = ns,
      fileInput(ns("csv_file"), "Upload CSV File", accept = ".csv")
    ),
    downloadButton(ns("download"), "Download CSV")
  )
}

# # Module UI for plotting
# weatherPlotUI <- function(id) {
#   ns <- NS(id)
#   tagList(
#     leafletOutput(ns("map"), height = "400px"),
#     plotlyOutput(ns("plot_temp")),
#     plotlyOutput(ns("plot_degree_days")),
#     plotlyOutput(ns("plot_tsi"))
#   )
# }

ui <- fluidPage(theme = shinytheme("cerulean"),
    tags$div(
      class = "jumbotron text-center", 
      style = "margin-bottom:0px;margin-top:0px",
      tags$h2(
        class = 'jumbotron-heading', 
        style = 'margin-bottom:0px;margin-top:0px', 'Hjernemark / Livtsja-vikke risiko app'
        ),
        p('Reindeer brainworm risk app')
    ),

    sidebarLayout(
      sidebarPanel(
        img(src='reindeer.jpg', align = "left", width = "100%"),
        weatherInputUI("weatherInput")
      ),
    
      mainPanel(
        # Tabs for different outputs
        tabsetPanel(
          id = "output_tabs",  # Optional: ID for the tabsetPanel
          
          
          # Tab 1: Hazard Map
          tabPanel(
            title = "Hazard Map",
            tags$div(
              style = "margin-bottom: 10px;",
              HTML("<p>Before using this app, read the READ ME tab.</p>"), 
             ),
            leafletOutput("map", height = "400px")  # Map output
          ),
          
          # Tab 2: Weather Data
          tabPanel(
            title = "Weather Data",
            plotlyOutput("plot_temp", height = "400px")  # Interactive temperature plot
          ),
          
          # Tab 3: Model Output (Degree Day and TSI Plots)
          tabPanel(
            title = "Model Output",
            fluidRow(
              column(12, plotlyOutput("plot_tsi", height = "400px")),  # Degree Day Plot
              column(12, plotlyOutput("plot_degree_days", height = "400px"))           # TSI Plot
            )
          ),
          
          # Tab 4: Data Table
          tabPanel(
            title = "Data Table",
            dataTableOutput("table")  # Data table output
          ),
          
          # Tab 0: Instructions
          tabPanel(
            title = "READ ME",
            div(
              "**Development version for veterinarians** This app is intended for use by veterinarians to help reindeer herders assess the risk of brainworm transmission based on recent weather conditions. Feedback is very welcome - please get in touch (hannah.vineer@liverpool.ac.uk)",
              style = "margin-top: 10px; font-size: 16px; font-weight: bold; color = #555;"
            ),
            div(
              HTML("
              <button class='btn btn-link' data-toggle='collapse' data-target='#additionalInfo' style='margin-top: 15px;'>
                About the predictions (click to expand)
              </button>
              <div id='additionalInfo' class='collapse'>
                <p style='font-size: 14px; font-style: italic; color: #555;'>
                  This app runs a brainworm Thermal Suitability Index (TSI) model <a href='https://doi.org/10.3389/fvets.2020.603990' target='_blank'>(Rose Vineer et al., 2021)</a> which uses daily weather data for your chosen locations to predict the approximate *timing* of brainworm transmission. Please note that the predictions generated by this app will be very sensitive to the date range of the data you request, and therefore the app must be used in collaboration with a veterinarian with expertise in brainworm.
                </p>
              </div>
            ")
            ),
            div(
              HTML("
              <button class='btn btn-link' data-toggle='collapse' data-target='#tabInfo' style='margin-top: 15px;'>
                What's in each tab? (click to expand)
              </button>
              <div id='tabInfo' class='collapse'>
                <p style='font-size: 14px; font-style: italic; color: #555;'>
                  *Hazard map* shows the predicted Thermal Suitability Index for your chosen locations and date range. You can zoom in/out, pan, and click on the locations for more information.
                  <br>*Weather data* shows the weather data extracted from the API or provided by you. Inspect this plot for any peculiarities before using the model output. 
                  <br>*Model output* shows the predicted Thermal Suitability Index over the range of your data, for each location, and the cumulative degree-days, on which the TSI predictions are based. Horizontal ablines show the theoretical TSI and degree-day thresholds, above whic, development from first to infective larval stage is completed in the gastropod host, and onward transmission to the reindeer is theoretically possible.
                  <br>*Data table* shows the raw weather data and predicted degree-days and TSI values. Inspect this table for any peculiarities before using the model output.
                  <br>The *Download CSV* button on the left allows you to download the raw data from the data table for further analyses. You can also interact with each of the plots and download those.</p>
              </div>
            ")
            ),
            div(
              HTML("
              <button class='btn btn-link' data-toggle='collapse' data-target='#runInfo' style='margin-top: 15px;'>
                How to run the app - using Visual Crossing weather API (click to expand)
              </button>
              <div id='runInfo' class='collapse'>
                <p style='font-size: 14px; font-style: italic; color: #555;'>
                  Based on your understanding of brainworm epidemiology and larval shedding in your region, choose an appropriate start date for the model predictions e.g. you may choose autumn to predict the timing of potential transmission of larvae shed by infected reindeer at this time of year. You will need to sign up for a free account at VisualCrossing.com and copy your API Key (can be found in the account section) to access the weather data. Once you have your API key, please input your requested locations for model predictions. We have added some default locations as examples and for users wishing to explore the app quickly. Bear in mind that the number of free records available through VisualCrossing is limited to 1000 per day, and therefore predicting TSI for a large number of locations over extended periods may not be possible with a free account.
                 </p>
              </div>
            ")
            ),
            div(
              HTML("
              <button class='btn btn-link' data-toggle='collapse' data-target='#csvInfo' style='margin-top: 15px;'>
                How to run the app - using your own weather data (click to expand)
              </button>
              <div id='csvInfo' class='collapse'>
                <p style='font-size: 14px; font-style: italic; color: #555;'>
                  If you already have your own weather data, you can upload this as a .csv file. The file must be formatted as follows: columns with the headers 'date', 'lat', 'lon', 'ID', 'mean_temp'. 'date' must be formatted as 'YYYY-MM-DD', for example, 1st of October 2024 would be '2024-10-01'. 'lat' and 'lon' are the latitudes and longitudes for the locations in your dataset, in *decimal degrees*. 'ID' is the name you give each location in your dataset, and will be used to label the visualisations produced by the app. Please keep these simple to avoid errors running the app. If you have multiple locations in your dataset, the data for each location should cover the same date range. *Troubleshooting* If your data upload fails or the temperature data look unusual/unexpected, you may have issues with special characters or incorrect formatting of dates.
                  </p>
              </div>
            ")
            ),
            div(
              HTML("
              <button class='btn btn-link' data-toggle='collapse' data-target='#interpretInfo' style='margin-top: 15px;'>
                Interpreting predictions (click to expand)
              </button>
              <div id='interpretInfo' class='collapse'>
                <p style='font-size: 14px; font-style: italic; color: #555;'>
                TSI>1 indicates that transmission is theoretically possible at that location based on the mean temperature data returned by the weather service and the assumption that larvae were shed at the beginning of your requested date range. 
                <br><br> We have colour-coded the map according to heuristic 'risk' levels. Low indicates that development of the larvae is not expected to have progressed significantly. Moderate indicates that some development has occurred and the larvae are approaching infective stage. Since the weather data provide only air temperature, we expect that transmission may occur in areas with Moderate risk if microcliatic conditions are warmer than air temperatures. High indicates that development to the infective stage is predicted to have been completed. And Very High indicates that weather conditions since the beginning of your date range have far exceeded the thermal requirements for transmission.  
                <br><br> Please note that this model currently only predicts the *timing* of transmission, and not the magnitude. We are currently working on modules which would also allow prediction of larval survival, to quantify the risk.
                <br><br> The model output presented in this version therefore represents the HAZARD component of risk assessment and should be interpreted in combination with local knowledge of exposure to potential infection (e.g. are reindeer grazing in that area, and were reindeer shedding larvae in that area earlier in the year?) and vulnerability (e.g. age and reproductive status, coinfection, nutritional/environmental stress). The app also provides the temperature data and model output for you to inspect/critically evaluate and download for reanalysis/archive.
                 </p>
              </div>
            ")
            ),
            div(
              HTML(
                '<p><br>Learn more about brainworm and elaphostrongylosis <a href="https://doi.org/10.1186/s13028-020-00524-4" target="_blank">here</a>.
                
                <br><br>Learn more about Thermal Suitability Index (TSI) <a href="https://doi.org/10.3389/fvets.2020.603990" target="_blank">here</a>.</p>'
              )
            )
          )
        )
      )
    )
  )
